export const contactObj = {
    owner1FirstName: '',
    owner1LastName: '',
    siteCarrierRoute: '',
    fullSiteAddress: '',
    siteAddressUnitNumber: '',
    fullMailAddress: '',
    mailAddressCity: '',
    mailAddressState: '',
    mailAddressZip: '',
    llcOwnerAgentName: '',
    phone1: '',
    phoneType1: '',
    phone2: '',
    phoneType2: '',
    phone3: '',
    phoneType3: '',
    phone4: '',
    phoneType4: '',
    phone5: '',
    phoneType5: '',
    phone6: '',
    phoneType6: '',
    phone7: '',
    phoneType7: '',
    email1: '',
    email2: '',
    email3: '',
    siteAddress: '',
    siteAddressCity: '',
    siteAddressState: '',
    siteAddressZip: '',
    
    useCodeDescription: '',
    useCodeCountyDescription: '',
    parcelNumber: '',
    bedrooms: '',
    bathrooms: '',
    buildingArea: '',
    lotAreaSQFT: '',
    lotAreaAcres: '',
    costPerSqFt: '',
    tract: '',
    yearBuilt: '',
    zoning: '',
    numberOfUnits: '',
    pool: '',
    ownerOccupied: '',
    ownerType: '',
    saleDate: '',
    salesPrice: '',
    salesPriceCode: '',
    salesDocumentNumber: '',
    deedType: '',
    assessedLandValue: '',
    totalAssessedValue: '',
    taxAmount: '',
    currentTaxYear: ''
  };

  export const contactObjArr = [
    'owner1FirstName',
    'owner1LastName',
    'siteCarrierRoute',
    'fullSiteAddress',
    'siteAddressUnitNumber',
    'fullMailAddress',
    'mailAddressCity',
    'mailAddressState',
    'mailAddressZip',
    'llcOwnerAgentName',
    'phone1',
    'phoneType1',
    'phone2',
    'phoneType2',
    'phone3',
    'phoneType3',
    'phone4',
    'phoneType4',
    'phone5',
    'phoneType5',
    'phone6',
    'phoneType6',
    'phone7',
    'phoneType7',
    'email1',
    'email2',
    'email3',
    'siteAddress',
    'siteAddressCity',
    'siteAddressState',
    'siteAddressZip',
    '',
    'useCodeDescription',
    'useCodeCountyDescription',
    'parcelNumber',
    'bedrooms',
    'bathrooms',
    'buildingArea',
    'lotAreaSQFT',
    'lotAreaAcres',
    'costPerSqFt',
    'tract',
    'yearBuilt',
    'zoning',
    'numberOfUnits',
    'pool',
    'ownerOccupied',
    'ownerType',
    'saleDate',
    'salesPrice',
    'salesPriceCode',
    'salesDocumentNumber',
    'deedType',
    'assessedLandValue',
    'totalAssessedValue',
    'taxAmount',
    'currentTaxYear'
];